import type { Metadata } from 'next';
import { Geist_Mono, Poppins } from 'next/font/google';
import './globals.css';
import { QueryProviders } from '@/providers/queryProviders';
import { ThemeProvider } from '@mui/material';
import { theme } from '@/styles/theme';
import { Toaster } from 'sonner';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '700'] });

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${geistMono.variable} antialiased`}>
        {/* <ToastContainer /> */}
        <QueryProviders>
          <Toaster position="top-right" richColors closeButton />
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </QueryProviders>
      </body>
    </html>
  );
}
