import type { Metadata } from 'next';
import { Geist_Mono, Poppins } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import './globals.css';
import { QueryProviders } from '@/providers/queryProviders';
import { ThemeProvider } from '@mui/material';
import { theme } from '@/styles/theme';
import { LoginProvider } from './(public)/login/hooks';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '700'] });

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${geistMono.variable} antialiased h-screen w-screen overflow-hidden`}
      >
        <ToastContainer />
        <QueryProviders>
          <ThemeProvider theme={theme}>
            <LoginProvider>{children}</LoginProvider>
          </ThemeProvider>
        </QueryProviders>
      </body>
    </html>
  );
}
